### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by afifwindow** [s4if/ppdb-sma#17]
mas bagi databasenya

**Comment by s4if** [comment]
kalo pake linux, perintahnya kayak gini...
touch application/db.sqlite
vendor/doctrine/orm/bin/doctrine orm:schema-tool:create

**Comment by s4if** [comment]
kalo mau download disini...
https://mega.nz/#!n0BlUYrR!eQtbNoduREetF0TyhykW2CH369JOJTMKNkT2RAStjRo

**Comment by afifwindow** [comment]
waduh saya pakai hosting om caranya gimana om?
pas saya ekspord ke phpmyadmin di hosting malah gagal om, mohon bantuannya om,, boleh minta wa nya om, makasih sebelumnya om, smoga murah rejeki dan sehat selalu

**Comment by s4if** [comment]
sqlite-nya cuma tinggal di copy paste ke folder application/ aja...
jangan di phpmyadmn... 
sebenarnya program ini ta desain jalannya di vps, jadi kalau di hostingan, sy ga tau...
nomer ta dm aja...
